# Generated by Django 4.2.29 on 2026-03-07 23:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ayah',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arabic', models.TextField(help_text='Arabic text of the ayah')),
                ('text', models.TextField(help_text='English translation')),
                ('surah', models.CharField(help_text='e.g. Al-Baqarah', max_length=100)),
                ('ayah_ref', models.CharField(help_text='e.g. 2:286', max_length=20)),
                ('mood', models.CharField(choices=[('lost', 'Feeling Lost'), ('anxious', 'Anxious'), ('grateful', 'Grateful'), ('hopeful', 'Hopeful'), ('general', 'General')], default='general', max_length=20)),
                ('is_daily', models.BooleanField(default=False, help_text='Feature as daily ayah')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Ayahs',
                'ordering': ['ayah_ref'],
            },
        ),
        migrations.CreateModel(
            name='GuidanceEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('is_ayah', models.BooleanField(default=False, help_text='Is this a Quranic reference?')),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='GuidanceTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(choices=[('tawakkul', 'Tawakkul'), ('sabr', 'Sabr'), ('iman', 'Iman'), ('shukr', 'Shukr')], unique=True)),
                ('title', models.CharField(max_length=100)),
                ('subtitle', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Habit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('habit_type', models.CharField(choices=[('fajr', 'Fajr Prayer'), ('dhuhr', 'Dhuhr Prayer'), ('asr', 'Asr Prayer'), ('maghrib', 'Maghrib Prayer'), ('isha', 'Isha Prayer'), ('quran', "Qur'an Reading"), ('dhikr', 'Dhikr'), ('custom', 'Custom')], max_length=20)),
                ('label', models.CharField(blank=True, help_text='Override default label', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='habits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['habit_type'],
                'unique_together': {('user', 'habit_type')},
            },
        ),
        migrations.CreateModel(
            name='HabitLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('completed', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('habit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='core.habit')),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('habit', 'date')},
            },
        ),
        migrations.RemoveField(
            model_name='islamiccontent',
            name='category',
        ),
        migrations.AlterModelOptions(
            name='reflection',
            options={'ordering': ['-created_at']},
        ),
        migrations.RenameField(
            model_name='reflection',
            old_name='content',
            new_name='text',
        ),
        migrations.AddField(
            model_name='reflection',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='reflection',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reflections', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='IslamicContent',
        ),
        migrations.AddField(
            model_name='guidanceentry',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='core.guidancetopic'),
        ),
    ]
